import './style.css'
import { workouts, fuelChoices } from './data.js'
import { loadState, saveState, todayKey, touchStreak, setStateUser, resetState } from './store.js'
import { supabase } from './supabase.js'
import { getSession, signIn, signUp, signOut } from './auth.js'
import { ActivityTracker, formatTime, formatPace } from './walk.js'
import { equipmentCatalog, chooseExercise, availableOptions, levelForWorkout, exerciseGuide } from './equipment.js'
import { foodGroups, portionOptions, estimatePoints, bmi } from './nutrition.js'
import { loadCloudState, loadWellbeing, addFood, saveWeighIn, saveProfileProgress, addActivity, saveCheckin, loadMemberDirectory, requestWorkoutMate, updateWorkoutMate } from './api.js'

let state=loadState(), view='today', session=null, timer=null, walker=null, walkStats=null, gpsMode='walk', wakeLock=null, syncMessage='', guideName=null, authMode='signin', publicView='auth', memberDirectory=[], mateRows=[]
const nav=[['today','Overview'],['move','Move'],['fuel','Fuel'],['setup','Set Up'],['journey','My Journey']]

const button=(id,label)=>`<button data-view="${id}">${label}</button>`
function layout(body){const publicNav=!session?'<button id="vision-link" class="account-action">The Vision</button>':nav.map(x=>button(...x)).join('')+'<button id="sign-out" class="account-action">Sign out</button>';return `<header><button class="brand" ${session?'data-view="today"':'id="public-home"'}>TRANSFORM <small>WITH ME</small></button><nav>${publicNav}</nav></header>${syncMessage?`<div class="sync-message">${syncMessage}</div>`:''}<main>${body}</main><footer><strong>CONSISTENT.</strong> <strong>PERSISTENT.</strong> <strong>TARGETED.</strong></footer>`}
function head(k,t,p){return `<section class="head"><p class="eyebrow">${k}</p><h1>${t}</h1><p>${p}</p></section>`}
function resolveWorkout(w){return {...w,exercises:w.slots.map((slot,i)=>{const override=state.exerciseOverrides?.[`${w.id}:${i}`],opts=availableOptions(slot.category,state.equipment||[],levelForWorkout(w.id)),picked=(override&&opts.find(x=>x.name===override))||chooseExercise(slot.category,state.equipment||[],w.id+i,levelForWorkout(w.id));return {name:picked?.name||'Bodyweight movement',category:slot.category,note:picked?.note||'Use a comfortable, controlled range.'}})}}
function today(){
 const w=resolveWorkout(workouts[state.workoutIndex%28]), f=Object.values(state.fuel[todayKey()]||{}).filter(Boolean).length
 return head('TODAY','Show up. <span>That counts.</span>','Do what fits today. The aim is consistency, not a perfect scorecard.')+`
 <section class="dashboard"><article class="feature"><div><p class="eyebrow">NEXT WORKOUT · ${w.id}/28</p><h2>${w.title}</h2><p>${w.focus} · ${w.minutes} min</p></div>${button('move','Go to Move →')}</article>
 ${[['Active minutes',state.activeMinutes],['Day streak',state.streak],['Healthy choices',f],['Water',state.hydrationByDate?.[todayKey()]||0]].map(x=>`<article class="stat"><strong>${x[1]}</strong><span>${x[0]}</span></article>`).join('')}</section>`}
function move(){
 const w=resolveWorkout(workouts[state.workoutIndex%28])
 return head('MOVE','Your next move.','Follow the sequence, replace it with another activity, or add extra movement. It all counts.')+`
 <section class="cols"><article class="feature workout"><div><p class="eyebrow">WORKOUT ${w.id} OF 28 · ${w.level.toUpperCase()}</p><h2>${w.title}</h2><p>${w.focus} · ${w.exercises.length} exercises · ${w.rounds} rounds</p><strong>~${w.minutes} minutes</strong></div><div class="workout-start"><label><input id="auto-progress" type="checkbox" ${state.autoProgress!==false?'checked':''}> Auto progression</label><button id="start-workout">Start workout →</button></div></article>
 <article class="form"><h3>Track an activity</h3><p class="hint">Track distance, pace and elevation with GPS.</p><div class="gps-buttons"><button data-gps="walk">Walk</button><button data-gps="run">Run</button><button data-gps="ride">Bike Ride</button><button data-gps="hike">Hike</button></div><hr><h3>Swimming</h3><p class="hint">Record a swim by time now; laps and distance are part of the swimming activity model.</p><button id="quick-swim">Log a swim →</button><hr><h3>Log another activity</h3><label>Activity<input id="activity" placeholder="Walk, swim, sport…"></label><label>Active minutes<input id="minutes" type="number" min="1" placeholder="30"></label><button id="log">Add activity</button><p class="hint">Your next workout stays waiting for you.</p></article></section>
 <section class="exercise-preview"><h3>Inside this workout</h3><div>${w.exercises.map((e,i)=>`<span><b>${i+1}</b><button class="exercise-name" data-guide="${e.name}">${e.name}<small>${e.category} · ${['','foundation','developing','stronger'][levelForWorkout(w.id)]}</small></button><button class="swap-exercise" data-swap="${i}" title="Choose another suitable exercise">Swap</button></span>`).join('')}</div></section><section class="history move-together"><p class="eyebrow">TOGETHER</p><h3>Better with a mate.</h3><p>Connect with someone in the programme for accountability. Your workout sequence remains your own.</p><button id="find-mate" class="text-button">Find a workout mate →</button><div id="mate-panel"></div></section><section class="history"><h3>Recent movement</h3>${state.activities.length?state.activities.slice(-5).reverse().map(a=>`<div><span>${a.name}</span><strong>${a.minutes} min</strong></div>`).join(''):'<p>Nothing logged yet.</p>'}</section>`}
function guideView(name){const w=timer?.workout||resolveWorkout(workouts[state.workoutIndex%28]),e=w.exercises.find(x=>x.name===name),g=exerciseGuide(name,e?.note||'');return head('EXERCISE GUIDE',name,g.summary)+`<section class="form narrow"><h3>How to do it</h3><ol>${g.steps.map(x=>`<li>${x}</li>`).join('')}</ol><h3>Technique cue</h3><p>${g.cues}</p><h3>Make it easier</h3><p>${g.easier}</p><button id="close-guide">Back to workout</button></section>`}
function buildIntervals(w){const steps=[];for(let r=1;r<=w.rounds;r++){w.exercises.forEach((e,i)=>{steps.push({kind:'work',name:e.name,note:e.note,seconds:w.workSeconds,round:r});if(!(r===w.rounds&&i===w.exercises.length-1))steps.push({kind:'rest',name:'Recover',note:'Next: '+(w.exercises[(i+1)%w.exercises.length]?.name||''),seconds:w.restSeconds,round:r})})}return steps}
function timerView(){const w=timer.workout||resolveWorkout(workouts[state.workoutIndex%28]),s=timer.steps[timer.index],pct=Math.round((timer.index/timer.steps.length)*100);return `<section class="timer-screen"><p class="eyebrow">WORKOUT ${w.id} · ROUND ${s.round} OF ${w.rounds}</p><div class="timer-progress"><i style="width:${pct}%"></i></div><p class="timer-kind">${s.kind==='rest'?'RECOVER':'MOVE'}</p><h1>${s.name}</h1>${s.kind==='work'?`<button id="timer-guide" class="secondary">How do I do this?</button>`:''}<div class="countdown">${Math.floor(timer.left/60)}:${String(timer.left%60).padStart(2,'0')}</div><p class="timer-note">${s.note}</p><div class="timer-actions"><button id="prev-step">← Previous</button><button id="toggle-timer">${timer.running?'Pause':'Start'}</button><button id="next-step">Skip →</button></div><button class="quit" id="quit-workout">Exit workout</button></section>`}
function startTimer(w){timer={workout:w,steps:buildIntervals(w),index:0,left:w.workSeconds,running:false,tick:null,endAt:null};view='timer';render()}
function advanceTimer(delta=1,autoStart=false){timer.index+=delta;if(timer.index<0)timer.index=0;if(timer.index>=timer.steps.length){finishWorkout();return}timer.left=timer.steps[timer.index].seconds;timer.endAt=null;cue(timer.steps[timer.index].kind==='rest'?440:660);render();if(autoStart&&state.autoProgress!==false){timer.running=true;timer.endAt=Date.now()+timer.left*1000;keepAwake();timer.tick=setInterval(refreshTimer,250);render()}}
async function keepAwake(){try{if('wakeLock'in navigator&&!wakeLock)wakeLock=await navigator.wakeLock.request('screen')}catch{}}
function releaseWake(){try{wakeLock?.release()}catch{}wakeLock=null}
function cue(freq=660){try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.05,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.12);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.12)}catch{}if(navigator.vibrate)navigator.vibrate(80)}
function refreshTimer(){if(!timer?.running||!timer.endAt)return;timer.left=Math.max(0,Math.ceil((timer.endAt-Date.now())/1000));const el=document.querySelector('.countdown');if(el)el.textContent=Math.floor(timer.left/60)+':'+String(timer.left%60).padStart(2,'0');if(timer.left<=0){clearInterval(timer.tick);timer.running=false;timer.endAt=null;advanceTimer(1,true)}}
async function runTimer(){timer.running=!timer.running;if(timer.running){timer.endAt=Date.now()+timer.left*1000;await keepAwake();cue(660);timer.tick=setInterval(refreshTimer,250)}else{refreshTimer();clearInterval(timer.tick);timer.endAt=null;releaseWake()}render()}
async function finishWorkout(){const w=timer?.workout||resolveWorkout(workouts[state.workoutIndex%28]);if(timer?.tick)clearInterval(timer.tick);releaseWake();timer=null;state.completedWorkouts.push({id:w.id,date:todayKey()});state.activities.push({name:w.title,minutes:w.minutes,date:todayKey()});state.activeMinutes+=w.minutes;state.workoutIndex=(state.workoutIndex+1)%28;state.exerciseOverrides={};touchStreak(state);if(session)await syncMovement({type:'workout',workoutNumber:w.id,name:w.title,minutes:w.minutes,date:todayKey()});view='move';commit()}
function swimView(){return head('SWIM','Log your swim.','Record what you know. Time is enough; laps, distance and intensity are optional.')+`<section class="form narrow"><label>Minutes<input id="swim-minutes" type="number" min="1" placeholder="30"></label><label>Laps <small>optional</small><input id="swim-laps" type="number" min="0" placeholder="20"></label><label>Distance (km) <small>optional</small><input id="swim-distance" type="number" min="0" step="0.01" placeholder="0.5"></label><label>Intensity<select id="swim-intensity"><option value="">Not recorded</option><option value="easy">Easy</option><option value="moderate">Moderate</option><option value="hard">Hard</option></select></label><div class="auth-actions"><button id="save-swim">Save swim</button><button id="cancel-swim" class="secondary">Cancel</button></div></section>`}
function walkView(){const s=walkStats||{elapsedSeconds:0,km:0,pace:0,elevationGain:0},label={walk:'Walk',run:'Run',ride:'Bike Ride',hike:'Hike'}[gpsMode]||'Activity';return `<section class="walk-live"><p class="eyebrow">LIVE ${label.toUpperCase()}</p><h1>Keep moving.</h1><p class="privacy-note">GPS tracking is active only for this walk. Your route is private by default.</p><section class="walk-stats"><article><strong id="walk-time">${formatTime(s.elapsedSeconds)}</strong><span>time</span></article><article><strong id="walk-distance">${s.km.toFixed(2)}</strong><span>km</span></article><article><strong id="walk-pace">${formatPace(s.pace)}</strong><span>avg pace</span></article><article><strong id="walk-elevation">${Math.round(s.elevationGain)} m</strong><span>elevation gain</span></article></section><section class="walk-guidance"><p class="eyebrow">GUIDANCE</p><h2>Steady walk</h2><p>Optional adaptive instructions will appear here. Always use your own judgement around roads, crossings and other hazards.</p></section><div class="walk-actions"><button id="finish-walk">Finish ${label}</button><button id="pause-gps" class="secondary">${s.paused?'Resume':'Pause'}</button><button id="cancel-walk" class="secondary">Cancel</button></div><p id="walk-error" class="hint"></p></section>`}
async function startGps(mode){gpsMode=mode;walkStats=null;view='walk';render();await keepAwake();walker=new ActivityTracker(stats=>{if(stats.error){const e=document.querySelector('#walk-error');if(e)e.textContent=stats.error;return}walkStats=stats;const t=document.querySelector('#walk-time'),d=document.querySelector('#walk-distance'),p=document.querySelector('#walk-pace'),g=document.querySelector('#walk-elevation');if(t)t.textContent=formatTime(stats.elapsedSeconds);if(d)d.textContent=stats.km.toFixed(2);if(p)p.textContent=formatPace(stats.pace);if(g)g.textContent=Math.round(stats.elevationGain)+' m'},{mode});try{walker.start()}catch(e){document.querySelector('#walk-error').textContent=e.message}}
async function finishWalk(){const s=walker?.stop();walker=null;releaseWake();if(s&&s.elapsedSeconds>0){const mins=Math.max(1,Math.round(s.elapsedSeconds/60));const label={walk:'GPS Walk',run:'GPS Run',ride:'GPS Bike Ride',hike:'GPS Hike'}[gpsMode]||'GPS Activity';state.activities.push({name:label,minutes:mins,date:todayKey(),distanceKm:+s.km.toFixed(2),elevationGain:Math.round(s.elevationGain),type:gpsMode});state.activeMinutes+=mins;touchStreak(state);if(session)await syncMovement({type:gpsMode,name:label,minutes:mins,date:todayKey(),distanceKm:+s.km.toFixed(2),elevationGain:Math.round(s.elevationGain)});saveState(state)}walkStats=null;view='move';render()}
function bindSwim(){document.querySelector('#cancel-swim').onclick=()=>{view='move';render()};document.querySelector('#save-swim').onclick=async()=>{const minutes=Math.round(Number(document.querySelector('#swim-minutes').value)),laps=Number(document.querySelector('#swim-laps').value)||null,distanceKm=Number(document.querySelector('#swim-distance').value)||null,intensity=document.querySelector('#swim-intensity').value||null;if(!(minutes>0))return;const item={name:'Swimming',minutes,date:todayKey(),type:'swim',laps,distanceKm,intensity};state.activities.push(item);state.activeMinutes+=minutes;touchStreak(state);if(session)await syncMovement(item);view='move';commit()}}
function bindWalk(){document.querySelector('#finish-walk').onclick=finishWalk;document.querySelector('#pause-gps').onclick=()=>{walker.paused?walker.resume():walker.pause();walkStats=walker.summary();render()};document.querySelector('#cancel-walk').onclick=()=>{walker?.stop();walker=null;releaseWake();walkStats=null;view='move';render()}}
function fuel(){
 const d=state.fuel[todayKey()]||{}, todays=(state.foodLog||[]).filter(x=>x.date===todayKey()), total=todays.reduce((n,x)=>n+x.points,0)
 return head('FUEL','Notice what you eat.','Food logging is for accountability, not perfection. Transform Points are a simple internal estimate based on food type and portion — not a clinical nutrition score.')+`<section class="cols"><article class="form"><h3>Log food</h3><label>What did you have?<input id="food-name" placeholder="e.g. toast and eggs"></label><label>Food type<select id="food-group">${foodGroups.map(x=>`<option value="${x[0]}">${x[2]}</option>`).join('')}</select></label><label>Portion<select id="food-portion">${portionOptions.map(x=>`<option value="${x[0]}">${x[2]}</option>`).join('')}</select></label><button id="log-food">Add food</button><p class="hint">Points are deliberately rough. They help you see patterns; they are not WeightWatchers Points and are not dietary advice.</p></article><article class="form"><h3>Today's food</h3><div class="points-total"><strong>${total}</strong><span>Transform Points</span></div>${todays.length?todays.slice().reverse().map(x=>`<div class="food-row"><span>${x.name}<small>${x.portion} · ${x.groupLabel}</small></span><strong>${x.points}</strong></div>`).join(''):'<p class="hint">Nothing logged yet.</p>'}</article></section><section class="choices">${fuelChoices.map(([id,label])=>`<button class="choice ${d[id]?'done':''}" data-fuel="${id}"><strong>${d[id]?'✓':'○'}</strong>${label}</button>`).join('')}<button class="choice water" id="water"><strong>+${state.hydrationByDate?.[todayKey()]||0}</strong>Log a drink of water</button></section>`
}
function progress(){
 const acts=state.activities||[], today=new Date(), days=Array.from({length:7},(_,i)=>{const d=new Date(today);d.setDate(today.getDate()-(6-i));return todayKey(d)}),
 weekly=days.map(d=>acts.filter(a=>a.date===d).reduce((n,a)=>n+(Number(a.minutes)||0),0)), weekTotal=weekly.reduce((a,b)=>a+b,0),
 n=state.completedWorkouts.length,p=Math.round(n/28*100), foods=state.foodLog||[], food7=foods.filter(x=>days.includes(x.date)),
 avgPoints=food7.length?Math.round(food7.reduce((n,x)=>n+x.points,0)/7):0, activeDays=days.filter(d=>acts.some(a=>a.date===d)).length,
 weights=(state.weighIns||[]).slice().sort((a,b)=>a.date.localeCompare(b.date)), latest=weights.at(-1), first=weights[0],
 weightChange=latest&&first&&weights.length>1?latest.weightKg-first.weightKg:null, max=Math.max(1,...weekly)
 return head('PROGRESS','Momentum, visible.','Look for patterns across movement, consistency, food accountability and body progress — not one perfect number.')+`
 <section class="progress-summary">
  <article><span>Last 7 days</span><strong>${weekTotal}</strong><small>active minutes</small></article>
  <article><span>Consistency</span><strong>${activeDays}/7</strong><small>active days</small></article>
  <article><span>Current streak</span><strong>${state.streak}</strong><small>days</small></article>
  <article><span>Food awareness</span><strong>${food7.length}</strong><small>items logged</small></article>
 </section>
 <section class="trend-grid"><article class="trend-card"><div class="trend-head"><div><p class="eyebrow">MOVEMENT</p><h3>7-day activity</h3></div><strong>${weekTotal} min</strong></div><div class="bar-chart">${weekly.map((v,i)=>`<div><i style="height:${Math.max(4,v/max*100)}%"></i><span>${['S','M','T','W','T','F','S'][new Date(days[i]+'T12:00:00').getDay()]}</span><small>${v}</small></div>`).join('')}</div></article>
 <article class="trend-card"><p class="eyebrow">PROGRAMME</p><div class="programme-progress"><div class="ring" style="--p:${p}"><strong>${p}%</strong></div><div><h3>${n} workouts completed</h3><p>Next: workout ${state.workoutIndex%28+1} of 28</p></div></div></article>
 <article class="trend-card"><p class="eyebrow">FUEL</p><h3>Accountability, not a scorecard</h3><div class="metric-line"><strong>${avgPoints}</strong><span>average Transform Points / day this week</span></div><p class="hint">Use this to notice your own patterns over time. A lower or higher number is not automatically “better”.</p></article>
 <article class="trend-card"><p class="eyebrow">BODY</p><h3>${latest?latest.weightKg.toFixed(1)+' kg':'No weigh-in yet'}</h3><p>${weightChange===null?'Weight tracking is optional.':(weightChange>0?'+':'')+weightChange.toFixed(1)+' kg across your recorded weigh-ins.'}</p><button data-view="body" class="text-button">View body progress →</button></article></section>
 <section class="badges">${[['First Move',acts.length>=1],['100 Minutes',state.activeMinutes>=100],['Consistent 7',state.streak>=7],['28 Strong',n>=28]].map(([x,e])=>`<article class="${e?'earned':''}"><strong>${x}</strong><span>${e?'Earned':'Still ahead'}</span></article>`).join('')}</section>`
}
function together(){return head('TOGETHER','Better with a mate.','Choose someone in the programme as your workout mate. Your own workout sequence still carries over.')+`<section class="form narrow"><label>Workout mate<input id="mate" value="${state.mate}" placeholder="Choose a member"></label><button id="save-mate">Connect workout mate</button>${state.mate?`<p class="success">Connected with <strong>${state.mate}</strong>.</p>`:''}</section>`}
function equipment(){const owned=new Set(state.equipment||[]);return head('MY EQUIPMENT','Build around what you have.','Transform can use your available equipment when selecting exercises. Update this whenever your setup changes.')+`<section class="equipment-grid">${equipmentCatalog.map(([id,label])=>`<label class="equipment-item ${owned.has(id)?'selected':''}"><input type="checkbox" data-equipment="${id}" ${owned.has(id)?'checked':''}><span>${label}</span></label>`).join('')}</section><p class="hint equipment-note">No equipment? That is fine — bodyweight options remain available.</p>`}
function body(){
 const weights=(state.weighIns||[]).slice().sort((a,b)=>a.date.localeCompare(b.date)), latest=weights.at(-1), value=latest?.weightKg, b=value&&state.heightCm?bmi(value,state.heightCm):null
 const points=weights.map((x,i)=>{const min=Math.min(...weights.map(w=>w.weightKg)),max=Math.max(...weights.map(w=>w.weightKg)),range=max-min||1;return `${weights.length===1?50:(i/(weights.length-1))*100},${90-((x.weightKg-min)/range)*80}`}).join(' ')
 return head('MY PROGRESS','More than one number.','Weight can be one optional measure of progress. Activity, consistency, strength, fitness and how you feel matter too.')+`<section class="body-grid"><article class="form"><h3>Weigh-in</h3><label>Weight (kg)<input id="weight-kg" type="number" min="20" max="400" step="0.1" value="${value||''}"></label><label>Height (cm) <small>optional, used for BMI</small><input id="height-cm" type="number" min="100" max="250" step="0.1" value="${state.heightCm||''}"></label><button id="save-weight">Save weigh-in</button><p class="hint">Weigh-ins are optional. BMI is shown as a screening calculation only and does not describe body composition, fitness or health by itself.</p></article><article class="body-summary"><p class="eyebrow">CURRENT</p><strong>${value?value.toFixed(1)+' kg':'—'}</strong><span>${b?'BMI '+b.toFixed(1):'Add height to calculate BMI'}</span></article></section>${weights.length?`<section class="weight-chart"><h3>Weight trend</h3><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="${points}" fill="none" vector-effect="non-scaling-stroke"/></svg><div><span>${weights[0].date}</span><span>${weights.at(-1).date}</span></div></section>`:''}`
}
function direction(){return head('MY DIRECTION','What are you moving toward?','Private to you. Keep it simple and meaningful.')+`<section class="form narrow"><label>My direction<textarea id="direction" rows="5" placeholder="What would transformation look like for me?">${state.direction}</textarea></label><button id="save-direction">Save my direction</button></section>`}
function setup(){return head('SET UP','Make Transform yours.','Set your direction, equipment and workout preferences in one place.')+`<section class="setup-grid"><article class="form setup-direction"><p class="eyebrow">MY DIRECTION</p><h2>What am I moving toward?</h2><label><textarea id="direction" rows="5" placeholder="What would transformation look like for me?">${state.direction}</textarea></label><button id="save-direction">Save my direction</button><p class="hint">Private to you. Your direction also appears in My Journey so you can keep it in view.</p></article><article class="form setup-preferences"><p class="eyebrow">WORKOUT SETTINGS</p><h2>How I want workouts to run</h2><label class="preference-toggle"><input id="setup-auto-progress" type="checkbox" ${state.autoProgress!==false?'checked':''}><span><strong>Auto progression</strong><small>Move automatically through exercise and recovery intervals.</small></span></label><p class="hint">You can still pause, skip or go back at any time.</p></article></section><section class="setup-section"><div class="section-heading"><div><p class="eyebrow">MY EQUIPMENT</p><h2>Build around what I have.</h2></div><p>Transform uses these choices when selecting suitable exercise options.</p></div><div class="setup-equipment-grid">${equipmentCatalog.map(([id,label])=>`<label class="equipment-item ${(state.equipment||[]).includes(id)?'selected':''}"><input type="checkbox" data-equipment="${id}" ${(state.equipment||[]).includes(id)?'checked':''}><span>${label}</span></label>`).join('')}</div></section><section class="setup-help"><div><p class="eyebrow">HELP</p><h3>Need a refresher?</h3><p>Revisit the Getting Started guide whenever you need it.</p></div><button data-view="getting-started" class="text-button">Getting Started →</button></section>`}
function journey(){return progress()+body()+`<section class="history"><p class="eyebrow">MY DIRECTION</p><h3>${state.direction||'Set your direction when you are ready.'}</h3><button data-view="setup" class="text-button">${state.direction?'Update my direction →':'Set my direction →'}</button></section>`}
function visionView(){return head('THE VISION','Transform With Me.','A practical accountability mission built around showing up consistently, working at your own level and continuing forward.')+`<section class="form narrow"><div class="video-placeholder"><p class="eyebrow">THE TRANSFORM WITH ME VISION</p><h2>Video coming soon.</h2><p>Hamish will share the mission behind Transform With Me here.</p></div><h3>Start where you are.</h3><p>Transform is designed around consistent action rather than perfection. The 28-workout sequence is cyclical: participate in the way that fits you, record what you do, and keep moving forward.</p><p>It is an accountability platform, not personal coaching or a promise of a particular result.</p><button id="vision-join">Join Transform With Me</button></section>`}
function gettingStartedView(){return head('GETTING STARTED','Welcome to the mission.','Everything you need to begin using Transform With Me.')+`<section class="form narrow"><div class="video-placeholder"><p class="eyebrow">MEMBER WELCOME</p><h2>Getting Started video coming soon.</h2><p>This video will explain the recurring 28-day challenge, how to use Transform in the way that suits you, and how to install it on your phone.</p></div><button data-view="today">Go to Today →</button></section>`}
function authView(){
 const signup=authMode==='signup'
 return `<section class="head"><p class="eyebrow">TRANSFORM WITH ME</p><h1>Start where you are.</h1><p>${signup?'Create your account and start your transformation.':'Sign in to keep your transformation progress with you.'}</p></section><section class="form narrow"><h3>${signup?'Create account':'Sign in'}</h3>${signup?'<label>Display name<input id="display-name" placeholder="Your name" autocomplete="name"></label>':''}<label>Email<input id="email" type="email" autocomplete="email"></label><label>Password<input id="password" type="password" autocomplete="${signup?'new-password':'current-password'}"></label><div class="auth-actions"><button id="auth-submit">${signup?'Create account':'Sign in'}</button></div><p class="auth-switch"><span>${signup?'Already have an account?':'New to Transform With Me?'}</span><button id="auth-toggle" type="button" class="text-action">${signup?'Sign in →':'Create an account →'}</button></p><p id="auth-message" class="hint"></p></section>`
}
function render(){if(guideName){document.querySelector('#app').innerHTML=layout(guideView(guideName));document.querySelector('#close-guide').onclick=()=>{guideName=null;render()};return}if(supabase&&!session){document.querySelector('#app').innerHTML=layout(publicView==='vision'?visionView():authView());bindPublic();return}if(view==='walk'){document.querySelector('#app').innerHTML=layout(walkView());bindWalk();return}if(view==='swim'){document.querySelector('#app').innerHTML=layout(swimView());bindSwim();return}if(view==='timer'&&timer){document.querySelector('#app').innerHTML=layout(timerView());bindTimer();return}const views={today,move,fuel,setup,journey,'getting-started':gettingStartedView};document.querySelector('#app').innerHTML=layout(views[view]());bind()}
function commit(){saveState(state);render()}
function cloudError(result,message='Saved on this device, but cloud sync failed.'){if(result?.error){syncMessage=message;return true}return false}
async function syncMovement(item){if(!session)return true;const activity=await addActivity(session.user.id,item);if(cloudError(activity))return false;const profile=await saveProfileProgress(session.user.id,{workout_index:state.workoutIndex,active_minutes:state.activeMinutes,streak:state.streak,last_active_date:state.lastActiveDate});if(cloudError(profile,'Activity saved, but your overall progress could not be updated in the cloud.'))return false;syncMessage='';return true}
async function hydrateCloud(){if(!supabase||!session?.user?.id)return;const uid=session.user.id;setStateUser(uid);state=loadState();const [cloud,well]=await Promise.all([loadCloudState(uid),loadWellbeing(uid)]);const loadErrors=[...(cloud.errors||[]),...(well.errors||[])];if(loadErrors.length){const sources=[...new Set(loadErrors.map(x=>x.source).filter(Boolean))];syncMessage='Some cloud data could not be loaded'+(sources.length?' ('+sources.join(', ')+')':'')+'. Your device copy is still available.';console.warn('Transform cloud load errors',loadErrors.map(x=>({source:x.source,code:x.error?.code,message:x.error?.message})))}else syncMessage='';if(cloud.profile){state.workoutIndex=cloud.profile.workout_index??state.workoutIndex;state.activeMinutes=cloud.profile.active_minutes??state.activeMinutes;state.streak=cloud.profile.streak??state.streak;state.lastActiveDate=cloud.profile.last_active_date??state.lastActiveDate;state.direction=cloud.profile.direction??state.direction;state.equipment=cloud.profile.equipment??state.equipment;state.heightCm=cloud.profile.height_cm??state.heightCm}state.activities=cloud.activities.map(x=>({name:x.name,minutes:x.minutes,date:x.activity_date,type:x.activity_type,workoutNumber:x.workout_number,distanceKm:x.distance_km==null?undefined:Number(x.distance_km),elevationGain:x.elevation_gain_m??undefined,laps:x.laps??undefined,intensity:x.intensity??undefined}));if(cloud.checkin){state.fuel[todayKey()]={'healthy-meal':cloud.checkin.healthy_meal,'snack':cloud.checkin.avoided_snacks,'drink':cloud.checkin.healthier_drinks,'fruit-veg':cloud.checkin.fruit_veg};state.hydrationByDate??={};state.hydrationByDate[todayKey()]=cloud.checkin.hydration||0}if(!cloud.checkin){state.fuel[todayKey()]={};state.hydrationByDate??={};state.hydrationByDate[todayKey()]=0}mateRows=cloud.mates||[];state.completedWorkouts=state.activities.filter(x=>x.type==='workout'&&x.workoutNumber).map(x=>({id:x.workoutNumber,date:x.date}));state.foodLog=well.food.map(x=>({id:x.id,date:x.eaten_date,name:x.name,group:x.food_group,groupLabel:foodGroups.find(g=>g[0]===x.food_group)?.[2]||x.food_group,portion:x.portion,points:x.points}));state.weighIns=well.weighIns.map(x=>({date:x.weigh_date,weightKg:Number(x.weight_kg)}));saveState(state);render()}
async function syncDailyCheckin(){const d=state.fuel[todayKey()]||{},r=await saveCheckin(session.user.id,todayKey(),{healthy_meal:!!d['healthy-meal'],avoided_snacks:!!d.snack,healthier_drinks:!!d.drink,fruit_veg:!!d['fruit-veg'],hydration:state.hydrationByDate?.[todayKey()]||0});if(cloudError(r))return false;const p=await saveProfileProgress(session.user.id,{streak:state.streak,last_active_date:state.lastActiveDate});if(cloudError(p,'Daily check-in saved, but your streak could not be updated in the cloud.'))return false;syncMessage='';return true}
function bindPublic(){document.querySelector('#vision-link')?.addEventListener('click',()=>{publicView='vision';render();scrollTo(0,0)});document.querySelector('#public-home')?.addEventListener('click',()=>{publicView='auth';render();scrollTo(0,0)});document.querySelector('#vision-join')?.addEventListener('click',()=>{publicView='auth';authMode='signup';render();scrollTo(0,0)});if(publicView==='auth')bindAuth()}
function bindAuth(){
 const email=()=>document.querySelector('#email').value.trim(), pass=()=>document.querySelector('#password').value, msg=document.querySelector('#auth-message')
 document.querySelector('#auth-toggle').onclick=()=>{authMode=authMode==='signin'?'signup':'signin';render()}
 document.querySelector('#auth-submit').onclick=async()=>{
  if(authMode==='signin'){const {data,error}=await signIn(email(),pass());if(error){msg.textContent=error.message;return}session=data.session;if(session)await hydrateCloud();render();return}
  const name=document.querySelector('#display-name').value.trim();if(!name){msg.textContent='Add your display name first.';return}
  const {data,error}=await signUp(email(),pass(),name);if(error){msg.textContent=error.message;return}session=data.session
  if(session){await hydrateCloud();render()}else msg.textContent='Check your email to confirm your account.'
 }
}
function bindTimer(){document.querySelector('#timer-guide')?.addEventListener('click',()=>{if(timer.tick)clearInterval(timer.tick);if(timer.running)refreshTimer();timer.running=false;timer.endAt=null;releaseWake();guideName=timer.steps[timer.index].name;render()});document.querySelector('#toggle-timer').onclick=runTimer;document.querySelector('#next-step').onclick=()=>{if(timer.tick)clearInterval(timer.tick);timer.running=false;advanceTimer()};document.querySelector('#prev-step').onclick=()=>{if(timer.tick)clearInterval(timer.tick);timer.running=false;advanceTimer(-1)};document.querySelector('#quit-workout').onclick=()=>{if(timer.tick)clearInterval(timer.tick);releaseWake();timer=null;view='move';render()}}
function bind(){
 document.querySelector('#sign-out')?.addEventListener('click',async()=>{await signOut();session=null;setStateUser(null);state=resetState();view='today';render()})
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();scrollTo(0,0)})
 document.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>{guideName=b.dataset.guide;render()});document.querySelectorAll('[data-swap]').forEach(b=>b.onclick=()=>{const w=resolveWorkout(workouts[state.workoutIndex%28]),i=+b.dataset.swap,slot=w.exercises[i],opts=availableOptions(slot.category,state.equipment||[],levelForWorkout(w.id));if(opts.length<2)return;const current=opts.findIndex(x=>x.name===slot.name),next=opts[(current+1)%opts.length];state.exerciseOverrides??={};state.exerciseOverrides[`${w.id}:${i}`]=next.name;saveState(state);render()})
 document.querySelector('#auto-progress')?.addEventListener('change',e=>{state.autoProgress=e.target.checked;saveState(state)});document.querySelector('#setup-auto-progress')?.addEventListener('change',e=>{state.autoProgress=e.target.checked;saveState(state);render()});document.querySelector('#start-workout')?.addEventListener('click',()=>startTimer(resolveWorkout(workouts[state.workoutIndex%28])))
 document.querySelectorAll('[data-gps]').forEach(b=>b.addEventListener('click',()=>startGps(b.dataset.gps)))
 document.querySelector('#quick-swim')?.addEventListener('click',()=>{view='swim';render()})
 document.querySelectorAll('[data-equipment]').forEach(x=>x.onchange=async()=>{const set=new Set(state.equipment||[]);x.checked?set.add(x.dataset.equipment):set.delete(x.dataset.equipment);state.equipment=[...set];if(session)cloudError(await saveProfileProgress(session.user.id,{equipment:state.equipment}));commit()})
 document.querySelector('#find-mate')?.addEventListener('click',async()=>{const panel=document.querySelector('#mate-panel');panel.innerHTML='<p class="hint">Loading members…</p>';const r=await loadMemberDirectory();if(r.error){panel.innerHTML='<p class="hint">Member list could not be loaded right now.</p>';return}memberDirectory=r.data||[];const connected=new Set(mateRows.filter(x=>x.status==='accepted').map(x=>x.requester_id===session.user.id?x.mate_id:x.requester_id));panel.innerHTML=memberDirectory.length?'<div class="member-list">'+memberDirectory.map(m=>'<div><strong>'+m.display_name+'</strong>'+(connected.has(m.user_id)?'<span class="success">Connected</span>':'<button data-mate-id="'+m.user_id+'">Connect</button>')+'</div>').join('')+'</div>':'<p class="hint">No other members are available yet.</p>';panel.querySelectorAll('[data-mate-id]').forEach(b=>b.onclick=async()=>{const r=await requestWorkoutMate(session.user.id,b.dataset.mateId);if(r.error){syncMessage='Workout mate request could not be sent.';render();return}b.outerHTML='<span class="hint">Request sent</span>'})})
 document.querySelector('#log')?.addEventListener('click',async()=>{const name=document.querySelector('#activity').value.trim(),minutes=+document.querySelector('#minutes').value;if(!name||minutes<1)return;state.activities.push({name,minutes,date:todayKey()});state.activeMinutes+=minutes;touchStreak(state);if(session)await syncMovement({type:'activity',name,minutes,date:todayKey()});commit()})
 document.querySelector('#log-food')?.addEventListener('click',async()=>{const name=document.querySelector('#food-name').value.trim(),group=document.querySelector('#food-group').value,portion=document.querySelector('#food-portion').value;if(!name)return;const groupLabel=foodGroups.find(x=>x[0]===group)?.[2]||group;const item={id:Date.now(),date:todayKey(),name,group,groupLabel,portion,points:estimatePoints(group,portion)};state.foodLog.push(item);if(session)cloudError(await addFood(session.user.id,item));touchStreak(state);commit()})
 document.querySelector('#save-weight')?.addEventListener('click',async()=>{const weight=Number(document.querySelector('#weight-kg').value),height=Number(document.querySelector('#height-cm').value);if(!(weight>0))return;if(height>0)state.heightCm=height;state.weighIns=state.weighIns.filter(x=>x.date!==todayKey());state.weighIns.push({date:todayKey(),weightKg:weight});if(session){cloudError(await saveWeighIn(session.user.id,todayKey(),weight));cloudError(await saveProfileProgress(session.user.id,{height_cm:state.heightCm}))}commit()})
 document.querySelectorAll('[data-fuel]').forEach(b=>b.onclick=async()=>{const d=todayKey();state.fuel[d]??={};state.fuel[d][b.dataset.fuel]=!state.fuel[d][b.dataset.fuel];touchStreak(state);if(session)await syncDailyCheckin();commit()})
 document.querySelector('#water')?.addEventListener('click',async()=>{state.hydrationByDate??={};state.hydrationByDate[todayKey()]=(state.hydrationByDate[todayKey()]||0)+1;touchStreak(state);if(session)await syncDailyCheckin();commit()})
 document.querySelector('#save-mate')?.addEventListener('click',()=>{state.mate=document.querySelector('#mate').value.trim();commit()})
 document.querySelector('#save-direction')?.addEventListener('click',async()=>{state.direction=document.querySelector('#direction').value.trim();if(session)cloudError(await saveProfileProgress(session.user.id,{direction:state.direction}));commit()})
}
async function start(){session=await getSession();if(session)await hydrateCloud();if(supabase){supabase.auth.onAuthStateChange(async(_event,s)=>{session=s;if(session)await hydrateCloud();else{setStateUser(null);state=resetState();render()}})}render()}
start()

document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){if(timer?.running)keepAwake();refreshTimer()}})
